/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adproc.coursework;

/**
 *
 * @author up790070
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        boxWidthTxtBx = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        boxLengthTxtBx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxHeightTxtBx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cardGradeCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        coloursCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bottomReinChckBx = new javax.swing.JCheckBox();
        cornerReinChckBx = new javax.swing.JCheckBox();
        sealableChckBx = new javax.swing.JCheckBox();
        quantityTxtBx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PlaceOrderBttn = new javax.swing.JButton();
        cancelBttn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        clearBttn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BuyABox");
        setBackground(new java.awt.Color(176, 211, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxWidthTxtBx.setNextFocusableComponent(boxLengthTxtBx);
        getContentPane().add(boxWidthTxtBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 22, 65, -1));

        jLabel1.setText("Width: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 25, -1, -1));

        boxLengthTxtBx.setNextFocusableComponent(boxHeightTxtBx);
        boxLengthTxtBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLengthTxtBxActionPerformed(evt);
            }
        });
        getContentPane().add(boxLengthTxtBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 48, 65, -1));

        jLabel2.setText("Length: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, -1, -1));

        boxHeightTxtBx.setNextFocusableComponent(cardGradeCombo);
        getContentPane().add(boxHeightTxtBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 74, 65, -1));

        jLabel3.setText("Height: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 77, -1, -1));

        cardGradeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        cardGradeCombo.setName(""); // NOI18N
        cardGradeCombo.setNextFocusableComponent(coloursCombo);
        cardGradeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardGradeComboActionPerformed(evt);
            }
        });
        getContentPane().add(cardGradeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 79, -1));

        jLabel4.setText("Card Grade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        coloursCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Colour", "One Colour", "Two Colour" }));
        coloursCombo.setNextFocusableComponent(bottomReinChckBx);
        getContentPane().add(coloursCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel5.setText("Colours:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        bottomReinChckBx.setText("Bottom Reinforcement");
        bottomReinChckBx.setNextFocusableComponent(cornerReinChckBx);
        getContentPane().add(bottomReinChckBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 112, -1, -1));

        cornerReinChckBx.setText("Corner Reinforcement");
        cornerReinChckBx.setNextFocusableComponent(sealableChckBx);
        getContentPane().add(cornerReinChckBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        sealableChckBx.setText("Sealable Top");
        sealableChckBx.setNextFocusableComponent(quantityTxtBx);
        getContentPane().add(sealableChckBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 138, -1, -1));

        quantityTxtBx.setNextFocusableComponent(cancelBttn);
        getContentPane().add(quantityTxtBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 40, -1));

        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        PlaceOrderBttn.setText("Place Order");
        PlaceOrderBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderBttnActionPerformed(evt);
            }
        });
        getContentPane().add(PlaceOrderBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        cancelBttn.setText("Cancel");
        cancelBttn.setNextFocusableComponent(PlaceOrderBttn);
        cancelBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBttnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        clearBttn.setText("Clear");
        clearBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBttnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel7.setText("Dimensions (cm)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        pack();
    }// </editor-fold>                        

    private void PlaceOrderBttnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void cancelBttnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }                                          

    private void boxLengthTxtBxActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void clearBttnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        boxWidthTxtBx.setText("");
        boxLengthTxtBx.setText("");
        boxHeightTxtBx.setText("");
        quantityTxtBx.setText("");
        bottomReinChckBx.setSelected(false);
        cornerReinChckBx.setSelected(false);
        sealableChckBx.setSelected(false);
        cardGradeCombo.setSelectedItem("Choose");
        coloursCombo.setSelectedItem("No Colour");
    }                                         

    private void cardGradeComboActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton PlaceOrderBttn;
    private javax.swing.JCheckBox bottomReinChckBx;
    private javax.swing.JTextField boxHeightTxtBx;
    private javax.swing.JTextField boxLengthTxtBx;
    private javax.swing.JTextField boxWidthTxtBx;
    private javax.swing.JButton cancelBttn;
    private javax.swing.JComboBox<String> cardGradeCombo;
    private javax.swing.JButton clearBttn;
    private javax.swing.JComboBox<String> coloursCombo;
    private javax.swing.JCheckBox cornerReinChckBx;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField quantityTxtBx;
    private javax.swing.JCheckBox sealableChckBx;
    // End of variables declaration                   
}
